import { copyFile, mkdir, rm, stat, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(scriptDirectory, '..');
const nodeModules = path.join(projectRoot, 'node_modules');
const vendorDirectory = path.join(projectRoot, 'assets', 'vendor');

const browserBundles = [
  ['vue/dist/vue.global.prod.js', 'vue/vue.global.prod.js'],
  ['marked/marked.min.js', 'marked/marked.min.js'],
  ['dompurify/dist/purify.min.js', 'dompurify/purify.min.js'],
  ['sortablejs/Sortable.min.js', 'sortablejs/Sortable.min.js'],
  ['localforage/dist/localforage.min.js', 'localforage/localforage.min.js'],
  ['jquery/dist/jquery.min.js', 'jquery/jquery.min.js'],
  ['@mhsdesign/jit-browser-tailwindcss/dist/cdn.min.js', 'tailwind-preview/tailwind-runtime.min.js'],
];

const fontFiles = [
  ['@fontsource-variable/lora/files/lora-latin-wght-normal.woff2', 'lora-latin-wght-normal.woff2'],
  ['@fontsource-variable/lora/files/lora-latin-wght-italic.woff2', 'lora-latin-wght-italic.woff2'],
  ['@fontsource/noto-serif-sc/files/noto-serif-sc-chinese-simplified-300-normal.woff2', 'noto-serif-sc-chinese-simplified-300-normal.woff2'],
  ['@fontsource/noto-serif-sc/files/noto-serif-sc-chinese-simplified-400-normal.woff2', 'noto-serif-sc-chinese-simplified-400-normal.woff2'],
  ['@fontsource/noto-serif-sc/files/noto-serif-sc-chinese-simplified-600-normal.woff2', 'noto-serif-sc-chinese-simplified-600-normal.woff2'],
  ['@fontsource/noto-serif-sc/files/noto-serif-sc-chinese-simplified-700-normal.woff2', 'noto-serif-sc-chinese-simplified-700-normal.woff2'],
  ['@fontsource/noto-serif-sc/files/noto-serif-sc-latin-300-normal.woff2', 'noto-serif-sc-latin-300-normal.woff2'],
  ['@fontsource/noto-serif-sc/files/noto-serif-sc-latin-400-normal.woff2', 'noto-serif-sc-latin-400-normal.woff2'],
  ['@fontsource/noto-serif-sc/files/noto-serif-sc-latin-600-normal.woff2', 'noto-serif-sc-latin-600-normal.woff2'],
  ['@fontsource/noto-serif-sc/files/noto-serif-sc-latin-700-normal.woff2', 'noto-serif-sc-latin-700-normal.woff2'],
  ['@fontsource/ma-shan-zheng/files/ma-shan-zheng-chinese-simplified-400-normal.woff2', 'ma-shan-zheng-chinese-simplified-400-normal.woff2'],
  ['@fontsource/ma-shan-zheng/files/ma-shan-zheng-latin-400-normal.woff2', 'ma-shan-zheng-latin-400-normal.woff2'],
];

const latinUnicodeRange = 'U+0000-024F,U+1E00-1EFF,U+2000-206F,U+20A0-20CF,U+2100-214F';
const cjkUnicodeRange = 'U+2E80-2EFF,U+2F00-2FDF,U+3000-303F,U+3040-30FF,U+3100-312F,U+31A0-31BF,U+31C0-31EF,U+3400-4DBF,U+4E00-9FFF,U+F900-FAFF,U+FE10-FE1F,U+FE30-FE6F,U+FF00-FFEF,U+20000-2FA1F';

function fontFace({ family, style = 'normal', weight, file, format = 'woff2', unicodeRange }) {
  return [
    '@font-face {',
    `  font-family: '${family}';`,
    `  font-style: ${style};`,
    '  font-display: swap;',
    `  font-weight: ${weight};`,
    `  src: url('./${file}') format('${format}');`,
    ...(unicodeRange ? [`  unicode-range: ${unicodeRange};`] : []),
    '}',
  ].join('\n');
}

const fontCss = [
  '/* Generated by scripts/prepare-vendor.mjs. */',
  fontFace({ family: 'Lora', weight: '400 700', file: 'lora-latin-wght-normal.woff2', format: 'woff2-variations' }),
  fontFace({ family: 'Lora', style: 'italic', weight: '400 700', file: 'lora-latin-wght-italic.woff2', format: 'woff2-variations' }),
  ...[300, 400, 600, 700].flatMap((weight) => [
    fontFace({ family: 'Noto Serif SC', weight, file: `noto-serif-sc-chinese-simplified-${weight}-normal.woff2`, unicodeRange: cjkUnicodeRange }),
    fontFace({ family: 'Noto Serif SC', weight, file: `noto-serif-sc-latin-${weight}-normal.woff2`, unicodeRange: latinUnicodeRange }),
  ]),
  fontFace({ family: 'Ma Shan Zheng', weight: 400, file: 'ma-shan-zheng-chinese-simplified-400-normal.woff2', unicodeRange: cjkUnicodeRange }),
  fontFace({ family: 'Ma Shan Zheng', weight: 400, file: 'ma-shan-zheng-latin-400-normal.woff2', unicodeRange: latinUnicodeRange }),
  '',
].join('\n\n');

async function copyFromNodeModules(sourceRelativePath, destinationRelativePath) {
  const sourcePath = path.join(nodeModules, sourceRelativePath);
  const destinationPath = path.join(vendorDirectory, destinationRelativePath);

  try {
    const sourceStat = await stat(sourcePath);
    if (!sourceStat.isFile()) throw new Error('source is not a file');
  } catch (error) {
    if (error?.code === 'ENOENT') {
      throw new Error(`Missing npm vendor input: ${sourceRelativePath}`);
    }
    throw error;
  }

  await mkdir(path.dirname(destinationPath), { recursive: true });
  await copyFile(sourcePath, destinationPath);
}

await rm(vendorDirectory, { recursive: true, force: true });

for (const [source, destination] of browserBundles) {
  await copyFromNodeModules(source, destination);
}

for (const [source, destination] of fontFiles) {
  await copyFromNodeModules(source, path.join('fonts', destination));
}

await writeFile(path.join(vendorDirectory, 'fonts', 'fonts.css'), fontCss, 'utf8');

console.log('RP-Hub vendor preparation complete');
console.log(`Browser bundles: ${browserBundles.length}`);
console.log(`Font files: ${fontFiles.length}`);
